image:
  tag: stable
  name: fsa-streamotion/configurable-hpa

resources: {}
  # Uncomment and set proper value some time ago
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
